// Auto-generated by scripts/generate-embedded-assets.js — do not edit
import _asset0 from "./dist/index.html" with { type: "file" };
import _asset1 from "./dist/assets/index-EEq53qDb.js.map" with { type: "file" };
import _asset2 from "./dist/assets/index-EEq53qDb.js" with { type: "file" };
import _asset3 from "./dist/assets/style-DuwbbE_Y.css" with { type: "file" };
import _asset4 from "./dist/app.js" with { type: "file" };
import _asset5 from "./dist/favicon.svg" with { type: "file" };

export const embeddedAssets = {
  "/index.html": { path: _asset0, mime: "text/html" },
  "/assets/index-EEq53qDb.js.map": { path: _asset1, mime: "application/json" },
  "/assets/index-EEq53qDb.js": { path: _asset2, mime: "application/javascript" },
  "/assets/style-DuwbbE_Y.css": { path: _asset3, mime: "text/css" },
  "/app.js": { path: _asset4, mime: "application/javascript" },
  "/favicon.svg": { path: _asset5, mime: "image/svg+xml" }
};
