// Auto-generated by scripts/generate-embedded-assets.js — do not edit
import _asset0 from "./dist/index.html" with { type: "file" };
import _asset1 from "./dist/assets/style-DA1Ma4YS.css" with { type: "file" };
import _asset2 from "./dist/assets/index-CItKJVeE.js" with { type: "file" };
import _asset3 from "./dist/assets/index-CItKJVeE.js.map" with { type: "file" };

export const embeddedAssets = {
  "/index.html": { path: _asset0, mime: "text/html" },
  "/assets/style-DA1Ma4YS.css": { path: _asset1, mime: "text/css" },
  "/assets/index-CItKJVeE.js": { path: _asset2, mime: "application/javascript" },
  "/assets/index-CItKJVeE.js.map": { path: _asset3, mime: "application/json" }
};
